import postgres from 'postgres';
import fs from 'node:fs';
const env = fs.readFileSync('.env.local','utf8').split('\n').reduce((a,l)=>{const m=l.match(/^([A-Z_]+)=(.+)$/);if(m)a[m[1]]=m[2].replace(/^"(.*)"$/,'$1');return a;},{});
const sql = postgres(env.SUPABASE_DB_URL);
const cols = await sql`select column_name, data_type from information_schema.columns where table_schema='public' and table_name='gift_templates' order by ordinal_position`;
console.log('gift_templates columns:');
cols.forEach(c => console.log(`  ${c.column_name.padEnd(28)} ${c.data_type}`));
const links = await sql`select column_name from information_schema.columns where table_schema='public' and table_name='gift_product_templates'`;
console.log(`\ngift_product_templates columns: ${links.map(c=>c.column_name).join(', ')}`);
const rows = await sql`select t.id, t.name, t.zones_json from gift_templates t join gift_product_templates l on l.template_id = t.id where l.product_id = '06cf7fe0-2f22-4903-8e28-e19adc156ed8'`;
console.log(`\nTemplates linked to song-lyrics-photo-frame: ${rows.length}`);
rows.forEach(r => console.log(`  ${r.name} [${r.id}]\n    zones=${JSON.stringify(r.zones_json).slice(0, 300)}`));
await sql.end();
